version: "3.3"
services:
  cloudreve:
    image: xavierniu/cloudreve
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai
    ports:
      - 5212:5212
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/cloudreve/uploads
      - ./config:/cloudreve/config
      - ./db:/cloudreve/db
      - ./avatar:/cloudreve/avatar
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  db:
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    image: mysql/mysql-server:8.0
    restart: always
    expose:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: vXMQBZ5oMimvCf
      MYSQL_PASSWORD: RWT65uzGFNPdik
      MYSQL_DATABASE: clodreve
      MYSQL_USER: clodreve
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  redis:
    image: redis:alpine
    restart: always
    command: --requirepass "3Z2Dsaue2VTL97"
    expose:
      - 6379
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"